return {
  { data = "string",   range = { 1, 6 },   type = "identifier" },
  { data = ".",        range = { 7, 7 },   type = "symbol" },
  { data = "byte",     range = { 8, 11 },  type = "identifier" },
  { data = "(",        range = { 12, 12 }, type = "symbol" },
  { data = "'",        range = { 13, 13 }, type = "string:start" },
  { data = "a",        range = { 14, 14 }, type = "string" },
  { data = "'",        range = { 15, 15 }, type = "string:end" },
  { data = ")",        range = { 16, 16 }, type = "symbol" },
  { data = "local",    range = { 18, 22 }, type = "keyword" },
  { data = "text",     range = { 24, 27 }, type = "identifier" },
  { data = "=",        range = { 29, 29 }, type = "operator" },
  { data = "'",        range = { 31, 31 }, type = "string:start" },
  { data = "a",        range = { 32, 32 }, type = "string" },
  { data = "'",        range = { 33, 33 }, type = "string:end" },
  { data = "..",       range = { 35, 36 }, type = "operator" },
  { data = "'",        range = { 38, 38 }, type = "string:start" },
  { data = "b",        range = { 39, 39 }, type = "string" },
  { data = "'",        range = { 40, 40 }, type = "string:end" },
  { data = "function", range = { 42, 49 }, type = "keyword" },
  { data = "printc",   range = { 51, 56 }, type = "identifier" },
  { data = "(",        range = { 57, 57 }, type = "symbol" },
  { data = "...",      range = { 58, 60 }, type = "vararg" },
  { data = ")",        range = { 61, 61 }, type = "symbol" },
  { data = "return",   range = { 65, 70 }, type = "keyword" },
  { data = "...",      range = { 72, 74 }, type = "vararg" },
  { data = "end",      range = { 76, 78 }, type = "keyword" }
}
