return {
  { data = "local",         range = { 1, 5 },     type = "keyword" },
  { data = "text0",         range = { 7, 11 },    type = "identifier" },
  { data = "=",             range = { 13, 13 },   type = "operator" },
  { data = "'",             range = { 15, 15 },   type = "string:start" },
  { data = '""ok?',         range = { 16, 20 },   type = "string" },
  { data = "'",             range = { 21, 21 },   type = "string:end" },
  { data = "local",         range = { 23, 27 },   type = "keyword" },
  { data = "text1",         range = { 29, 33 },   type = "identifier" },
  { data = "=",             range = { 35, 35 },   type = "operator" },
  { data = '"',             range = { 37, 37 },   type = "string:start" },
  { data = "''ok?",         range = { 38, 42 },   type = "string" },
  { data = '"',             range = { 43, 43 },   type = "string:end" },
  { data = "local",         range = { 45, 49 },   type = "keyword" },
  { data = "text2",         range = { 51, 55 },   type = "identifier" },
  { data = "=",             range = { 57, 57 },   type = "operator" },
  { data = "[[",            range = { 59, 60 },   type = "string:start" },
  { data = "[=[]=]ok?",     range = { 61, 69 },   type = "string" },
  { data = "]]",            range = { 70, 71 },   type = "string:end" },
  { data = "local",         range = { 73, 77 },   type = "keyword" },
  { data = "text3",         range = { 79, 83 },   type = "identifier" },
  { data = "=",             range = { 85, 85 },   type = "operator" },
  { data = "[==[",          range = { 87, 90 },   type = "string:start" },
  { data = "[[]][=[]=]ok?", range = { 91, 103 },  type = "string" },
  { data = "]==]",          range = { 104, 107 }, type = "string:end" }
}
