return {
  { data = "local", range = { 1, 5 },   type = "keyword" },
  { data = " ",     range = { 6, 6 },   type = "whitespace" },
  { data = "test0", range = { 7, 11 },  type = "identifier" },
  { data = " ",     range = { 12, 12 }, type = "whitespace" },
  { data = "=",     range = { 13, 13 }, type = "operator" },
  { data = " ",     range = { 14, 14 }, type = "whitespace" },
  { data = "1",     range = { 15, 15 }, type = "number" },
  { data = "\n",    range = { 16, 16 }, type = "whitespace" },
  { data = "\n",    range = { 17, 17 }, type = "whitespace" },
  { data = "\n",    range = { 18, 18 }, type = "whitespace" },
  { data = "\n",    range = { 19, 19 }, type = "whitespace" },
  { data = "\n",    range = { 20, 20 }, type = "whitespace" },
  { data = "\n",    range = { 21, 21 }, type = "whitespace" },
  { data = "\n",    range = { 22, 22 }, type = "whitespace" },
  { data = "local", range = { 23, 27 }, type = "keyword" },
  { data = " ",     range = { 28, 28 }, type = "whitespace" },
  { data = "test1", range = { 29, 33 }, type = "identifier" },
  { data = " ",     range = { 34, 34 }, type = "whitespace" },
  { data = "=",     range = { 35, 35 }, type = "operator" },
  { data = " ",     range = { 36, 36 }, type = "whitespace" },
  { data = "2",     range = { 37, 37 }, type = "number" },
  { data = "\n",    range = { 38, 38 }, type = "whitespace" }
}
