return {
  {data="string", posEnd=6, posStart=1, type="identifier"},
  {data=".", posEnd=7, posStart=7, type="symbol"},
  {data="byte", posEnd=11, posStart=8, type="identifier"},
  {data="(", posEnd=12, posStart=12, type="symbol"},
  {data="'", posEnd=13, posStart=13, type="string:start"},
  {data="a", posEnd=14, posStart=14, type="string"},
  {data="'", posEnd=15, posStart=15, type="string:end"},
  {data=")", posEnd=16, posStart=16, type="symbol"},
  {data="local", posEnd=22, posStart=18, type="keyword"},
  {data="text", posEnd=27, posStart=24, type="identifier"},
  {data="=", posEnd=29, posStart=29, type="operator"},
  {data="'", posEnd=31, posStart=31, type="string:start"},
  {data="a", posEnd=32, posStart=32, type="string"},
  {data="'", posEnd=33, posStart=33, type="string:end"},
  {data="..", posEnd=36, posStart=35, type="operator"},
  {data="'", posEnd=38, posStart=38, type="string:start"},
  {data="b", posEnd=39, posStart=39, type="string"},
  {data="'", posEnd=40, posStart=40, type="string:end"},
  {data="function", posEnd=49, posStart=42, type="keyword"},
  {data="printc", posEnd=56, posStart=51, type="identifier"},
  {data="(", posEnd=57, posStart=57, type="symbol"},
  {data="...", posEnd=60, posStart=58, type="vararg"},
  {data=")", posEnd=61, posStart=61, type="symbol"},
  {data="return", posEnd=70, posStart=65, type="keyword"},
  {data="...", posEnd=74, posStart=72, type="vararg"},
  {data="end", posEnd=78, posStart=76, type="keyword"}
}
