return {
  {data="local", posEnd=5, posStart=1, type="keyword"},
  {data="text0", posEnd=11, posStart=7, type="identifier"},
  {data="=", posEnd=13, posStart=13, type="operator"},
  {data="'", posEnd=15, posStart=15, type="string:start"},
  {data='""ok?', posEnd=20, posStart=16, type="string"},
  {data="'", posEnd=21, posStart=21, type="string:end"},
  {data="local", posEnd=27, posStart=23, type="keyword"},
  {data="text1", posEnd=33, posStart=29, type="identifier"},
  {data="=", posEnd=35, posStart=35, type="operator"},
  {data='"', posEnd=37, posStart=37, type="string:start"},
  {data="''ok?", posEnd=42, posStart=38, type="string"},
  {data='"', posEnd=43, posStart=43, type="string:end"},
  {data="local", posEnd=49, posStart=45, type="keyword"},
  {data="text2", posEnd=55, posStart=51, type="identifier"},
  {data="=", posEnd=57, posStart=57, type="operator"},
  {data="[[", posEnd=60, posStart=59, type="string:start"},
  {data="[=[]=]ok?", posEnd=69, posStart=61, type="string"},
  {data="]]", posEnd=71, posStart=70, type="string:end"},
  {data="local", posEnd=77, posStart=73, type="keyword"},
  {data="text3", posEnd=83, posStart=79, type="identifier"},
  {data="=", posEnd=85, posStart=85, type="operator"},
  {data="[==[", posEnd=90, posStart=87, type="string:start"},
  {data="[[]][=[]=]ok?", posEnd=103, posStart=91, type="string"},
  {data="]==]", posEnd=107, posStart=104, type="string:end"}
}
